name: Daily Lorviqua News Mailer

on:
  schedule:
    # 한국 시간 기준 매일 아침 08:00 실행 (UTC 23:00)
    - cron: '0 23 * * *'
  workflow_dispatch: # 웹에서 버튼 눌러 수동 실행 허용

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          SEARCH_KEYWORD: '로비큐아 OR 롤라티닙'
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PW: ${{ secrets.SENDER_PW }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python main.py
